### ISSUE TITLE
Operator writes error logs constantly when the obsolote CRD doesn't exist in the cluster

### ISSUE THREAD

**Issue by aliok** [knative/eventing-operator#112]
**Describe the bug**

Operator writes error logs constantly when the obsolote CRD doesn't exist in the cluster:
```
E0220 11:27:48.894624       1 reflector.go:123] knative.dev/pkg/controller/controller.go:456: Failed to list *v1alpha1.Eventing: the server could not find the requested resource (get eventings.operator.knative.dev)
```

It doesn't do anything when it is in this state.

**Expected behavior**
Properly skip watching of obsolete CRD when it doesn't exist. 

Also, no Error logs.
Even better --> a warn log like "Obsolete CRD doesn't exist in the cluster. Skipping obsolote CRD checks"

**To Reproduce**
Deploy operator on a cluster with no obsolote CRD existing on the cluster.
Create a CR for the new CRD.
Operator won't do anything and write the error log above constantly.
Create the obsolote CRD and operator will start creating the Knative eventing controllers immediately.

**Knative release version**
0.12: gcr.io/knative-releases/knative.dev/eventing-operator/cmd/manager@sha256:294a0fcfa6c206f49c56b299c4377d27a8ac420aafa18243874ef8b7e28859c0

**Additional context**
Add any other context about the problem here such as proposed priority

**Comment by houshengbo** [comment]
@aliok This was why we put the old CRD in the released YAML for 0.12 here: https://github.com/knative/eventing-operator/releases/download/v0.12.0/eventing-operator.yaml,
and I suggested to add the old CRD into the CSV for operatorhub as well.

When we deploy 0.12 on a cluster with no obsolete CRD, the obsolete CRD will be created. I am not sure how this issue still came over.

**Comment by aliok** [comment]
I think if it is not a big task, we can make the operator ignore the fact the old CRD doesn't exist.

Let me try this some time

**Comment by aliok** [comment]
/close

We don't have this problem with the newer versions
