### ISSUE TITLE
 checks version of deployment matches version go file

### ISSUE THREAD

**Issue by matzew** [knative/eventing-operator#23]
Task:

Change the controller to look for the `evening.knative.dev/release` label in the manifest and use that to set the status.version in the CR.

Add a test for that too

**Comment by aliok** [comment]
@matzew 

> Change the controller to look for the evening.knative.dev/release label in the manifest and use that to set the status.version in the CR.

Now that the versions are consistent (I mean after my PR is merged), doesn't really matter where the version info comes from.
