### ISSUE TITLE
Eventing operator should install core things and then IMC related things

### ISSUE THREAD

**Issue by aliok** [knative/eventing-operator#28]
At the moment, eventing operator first installs the `0.10.0-imc.yaml` file and then `0.10.0.yaml`.
This causes some problems as the `imc-dispatcher` fails until the `config-tracing` is installed with  `0.10.0.yaml`.  Eventually problems resolve automatically, but in my experiments it caused some unnecessary confusion.

I was originally suggest that we simply use a single file, the `release.yaml` file [here](https://github.com/knative/eventing/releases/download/v0.10.0/release.yaml) but I saw https://github.com/knative/eventing-operator/issues/13.

@houshengbo I saw your ticket https://github.com/knative/eventing-operator/issues/13. Is it already the case that we can configure installation with or without IMC?

**Comment by houshengbo** [comment]
@aliok Not yet.
We so far decided to install IMC anyway regardless of the options, since it is another tough question we need to resolve to install operators based on configurations across both eventing and serving operators.
