### ISSUE TITLE
Operator fails if `config-logging` and `config-observability` CMs don't exist

### ISSUE THREAD

**Issue by aliok** [knative/eventing-operator#29]
When installing the operator with `ko apply -f config/` everything works fine as there are 2 YAML files in `config/` for those configMaps.

I am trying to install the operator with [OLM](https://github.com/operator-framework/operator-lifecycle-manager) and operator crashes because those 2 configMaps don't exist.
OLM doesn't allow creating a configMap along with the operator deployment at the moment.

Those configMaps are essentially just blank:
* https://github.com/knative/eventing-operator/blob/05816afbb9183f79413326c72b25995d15c17df5/config/config-logging.yaml 
*https://github.com/knative/eventing-operator/blob/05816afbb9183f79413326c72b25995d15c17df5/config/config-observability.yaml

I say we should either:
A. Make operator create those configMaps if they don't exist
B. Don't make operator fail if the configMaps don't exist

**Comment by houshengbo** [comment]
@aliok This is true at this moment. I was trying to fix them in knative/pkg, but no luck.

I am even working on a PR for the operatorhub.io here: https://github.com/operator-framework/community-operators/pull/880
these two configmaps are the hurdle as well.

**Comment by aliok** [comment]
@houshengbo so, same thing also happens in serving? I can create an issue there too.

**Comment by houshengbo** [comment]
@aliok Right. It happened in both serving and eventing operators.
I committed a PR in knative/pkg to resolve it: https://github.com/knative/pkg/pull/872, but I am not whether it is in the favor.

**Comment by houshengbo** [comment]
We have resolved this issue after updating the dependency of knative/pkg with knative/pkg#872 merged.
