### ISSUE TITLE
CRD options for image registry and namespace

### ISSUE THREAD

**Issue by kramvan1** [knative/eventing-operator#83]
**Problem**

The images the operator lays down could be from a different image registry hub. (for security and scanning reasons).   Therefore need a way in the CRD to specify the image registry 

Something simple like:   `hub:  myhub.io`

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)**
Which persona is this feature for?
Event consumer (developer)

**Exit Criteria**

The image regs in the yaml manifest generated by the operator has the custom image registry hub.

**Time Estimate (optional):**
How many developer-days do you think this may take to resolve? 1

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by houshengbo** [comment]
@kramvan1 
Is it something similar to https://github.com/knative/serving-operator/blob/master/config/300-serving-v1alpha1-knativeserving-crd.yaml#L70, as in serving-operator?
