### ISSUE TITLE
Removal of sources-controller after 0.12.0

### ISSUE THREAD

**Issue by houshengbo** [knative/eventing-operator#90]
Based on the change here: https://github.com/knative/eventing/pull/2448
It is time for operator to shine, in terms of upgrade without manual interruption.

**Comment by aliok** [comment]
I can implement this

**Comment by houshengbo** [comment]
@aliok PLZ be advised that I am thinking of extending the scope of our tests-on-latest-eventing t verify the upgrade: https://github.com/knative/eventing-operator/pull/93. Hope we do not overlap our work.

**Comment by aliok** [comment]
Some notes:
- Reconciliation will be updating existing resources and create new resources
- It won't be able to delete the old resources (that is removed in eventing manifest)

So, I wrote a small [script](https://gist.github.com/aliok/54058292e90c3e6cf47c04b9f3266497) where I feed the 0.12 manifest (`gsutil cp gs://knative-releases/eventing/previous/v0.12.0/eventing.yaml ./`) and latest nightly manifest (`gsutil cp gs://knative-nightly/eventing/latest/eventing.yaml ./`) to make sure we will cover all resources that were deleted.

This is the output:
```
Unable to find 1.2.0 resource in nightly: apiVersion:v1 kind:ServiceAccount name:eventing-source-controller
Unable to find 1.2.0 resource in nightly: apiVersion:rbac.authorization.k8s.io/v1 kind:ClusterRole name:knative-eventing-source-controller
Unable to find 1.2.0 resource in nightly: apiVersion:rbac.authorization.k8s.io/v1 kind:ClusterRoleBinding name:eventing-source-controller
Unable to find 1.2.0 resource in nightly: apiVersion:rbac.authorization.k8s.io/v1 kind:ClusterRoleBinding name:eventing-source-controller-resolver
Unable to find 1.2.0 resource in nightly: apiVersion:apps/v1 kind:Deployment name:sources-controller
```

These are the things we need to delete in the operator

**Comment by aliok** [comment]
More changes needed after https://github.com/knative/eventing/pull/2519
