### ISSUE TITLE
Migrate source apis to new api group

### ISSUE THREAD

**Issue by aliok** [knative/eventing-operator#91]
See these:
- KafkaSource: https://github.com/knative/eventing-contrib/issues/863
- GithubSource: https://github.com/knative/eventing-contrib/issues/862
- PrometheusSource: https://github.com/knative/eventing-contrib/issues/864
- AWSSQSSource: https://github.com/knative/eventing-contrib/issues/865
- CouchDBSource: https://github.com/knative/eventing-contrib/issues/866

and, other sources.

**Comment by aliok** [comment]
@houshengbo can't add the `upgrade` label myself to the ticket.

**Comment by houshengbo** [comment]
@aliok I don't think operator touches any sources from eventing-contrib. It is only limited to eventing core.

**Comment by aliok** [comment]
LOL, yes. Closing this one.
