### ISSUE TITLE
Support reading KubeConfig from KUBECONFIG env var

### ISSUE THREAD

**Issue by aliok** [knative/eventing-operator#99]
We don't currently support reading KubeConfig from `KUBECONFIG` env var and because of that the OLM scorecard tests fail. See https://github.com/operator-framework/community-operators/pull/1192

We support passing the masterUrl and kubeconfig as command line arguments only.

BTW, I think we need to skip having 0.12 on OperatorHub because we wouldn't make a new release only for this ticket.

I closed the ticket at Operator Hub https://github.com/operator-framework/community-operators/pull/1192

**Comment by houshengbo** [comment]
@aliok We can skip 0.12.0, but we can have 0.12.x as we are/will be releasing as a INDEPENDENT project. If this is a crucial fix for operator, it is also an example that operator should backport to the 0.12 release.
